"""adding m2m field

Revision ID: 8947c035b1c0
Revises: 47c2c228b3ce
Create Date: 2024-06-09 17:34:19.177051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8947c035b1c0'
down_revision = '47c2c228b3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredient',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_constraint('ingredient_ibfk_1', type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('quantity', mysql.VARCHAR(length=64), nullable=True))
        batch_op.create_foreign_key('ingredient_ibfk_1', 'recipe', ['recipe_id'], ['id'])

    op.drop_table('recipe_ingredient')
    # ### end Alembic commands ###
